### ISSUE TITLE
init(num_pixels) never returns

### ISSUE THREAD

**Issue by tsuckow** [raspberry-node/node-rpi-ws281x-native#32]
I had been using the December 8th version just fine. Now after putting it on a new pi and ending up with the latest node and this library, init() never returns.

**Comment by tsuckow** [comment]
It is making it to ws2811_init, but that never returns. Which is interesting since the test executable in the submodule works.

**Comment by tsuckow** [comment]
The bug is in the submodule, sorry for the noise
Fix: https://github.com/allgoewer/rpi_ws281x/commit/46c8a4c1218ce999bb6371b2a20edce2c6a0bfee

**Comment by usefulthink** [comment]
thank you for pointing that out, i will see to it that i get the referenced commit merged into the version of the submodule we're using here.
